NoComments: Keine Kommentare
Submit: Veröffentlichen
NewComment: Neuer Kommentar
Cancel: Abbrechen
Reply: Reply
Anonymous: Anonymous
Add: Hinzufügen
DeleteCategories: Kategorien löschen
AddNewEntry: Neuen Eintrag hinzufügen
PublishedOn date: Veröffentlicht am #{date}
CommentCount n@Int: #{show n} #{plural n "Kommentar" "Kommentare"}
Comments: Kommentare
Attachments: Anhänge
Attachment: Anhang
Delete': Löschen
Edit: Bearbeiten
Name: Name
Comment: Kommentar
Title: Titel
Ident: Ident
Tags: Tags
Summary: Zusammenfassung
Text: Text
Category: Category
