NoComments: No comments
Submit: Submit
NewComment: Leave a Reply
Cancel: Cancel
Anonymous: Anonymous
Add: Add
DeleteCategories: Delete categories
AddNewEntry: Add new entry
PublishedOn date@UTCTime: Published on #{date}
PublishedIn: Published in
CommentCount n@Int: #{show n} #{plural n "comment" "comments"}
Comments: Comments
Attachments: Attachments
Attachment: Attachment
Delete': Delete
Edit: Edit
Name: Name (optional)
Comment: Comment
AtDateWrote date@UTCTime: on #{date} wrote
Reply: Reply
Title: Title
Ident: Ident
Summary: Summary
Text: Text
Category: Category
PrivacyPolicy: Privacy Policy