NoComments: No comments
Submit: Submit
NewComment: Leave a Reply
Cancel: Cancel
Reply: Antworten
Anonymous: Anonymous
Add: Add
DeleteCategories: Delete categories
AddNewEntry: Add new entry
PublishedOn date@UTCTime: Published on #{date}
CommentCount n@Int: #{show n} #{plural n "comment" "comments"}
Comments: Comments
Attachments: Attachments
Attachment: Attachment
Delete': Delete
Edit: Edit
Name: Name
Comment: Comment
Title: Title
Ident: Ident
Tags: Tags
Summary: Summary
Text: Text
Category: Category