Default: &defaults
  host: "localhost"
  port: 3000
  copyright: Dieser Inhalt steht unter einer <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/de/" title="Lizenz">Creative Commons Lizenz</a>
  #analytics: Don't use Google Analytics!

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "https://www.pascal-wittmann.de"
  host: "127.0.0.1"
  port: 3001
  <<: *defaults
